project_id = "hthupflasjifsweetqhx"

[functions.blocking-script]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-overdue]
verify_jwt = false
